// ./_components/ai-fixed-quiz-generator.jsx
"use client";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label"; // Assuming you have a Label component
import { Textarea } from "@/components/ui/textarea";
import { useState } from "react";
import { toast } from "sonner";
// import axios from "axios"; // For actual API call
import { Loader2 } from "lucide-react";
import { ManualQuizEditor } from "./manual-quiz-editor"; // To display/edit generated questions

// Mock API
const generateFixedQuizAPI = async (quizId, data) => {
  console.log("Generating fixed AI quiz:", quizId, data);
  // const response = await axios.post(`/api/quiz-sets/${quizId}/generate-fixed`, data);
  // return response.data.questions; // Assuming API returns the generated questions
  await new Promise(resolve => setTimeout(resolve, 2000)); // Simulate delay
  return [
    { id: "ai-q1", type: "mcq", prompt: "AI Generated: What is React?", options: [{label: "A library", isCorrect: true}, {label: "A framework", isCorrect: false}], explanation: "React is a JS library.", mark:1, order:0 },
    { id: "ai-q2", type: "short_answer", prompt: "AI Generated: What is the capital of France?", correctAnswer: "Paris", explanation: "Paris is the capital.", mark:1, order:1 },
  ];
}


export const AIFixedQuizGenerator = ({ quizData, setQuizData }) => {
  const [aiPrompt, setAiPrompt] = useState(quizData.aiPrompt || "");
  const [contextText, setContextText] = useState(""); // For direct text input
  const [contextFile, setContextFile] = useState(null);
  const [targetMcq, setTargetMcq] = useState(quizData.targetMcqCount || 5);
  const [targetShort, setTargetShort] = useState(quizData.targetShortAnswerCount || 2);
  // Add targetLong if needed based on your model
  const [isGenerating, setIsGenerating] = useState(false);

  const handleFileChange = (event) => {
    setContextFile(event.target.files[0]);
  };

  const handleGenerate = async () => {
    if (!aiPrompt && !contextText && !contextFile) {
      toast.error("Please provide a prompt or context data.");
      return;
    }
    setIsGenerating(true);
    try {
      const formData = new FormData();
      formData.append("quizId", quizData.id);
      formData.append("aiPrompt", aiPrompt);
      formData.append("targetMcqCount", targetMcq);
      formData.append("targetShortAnswerCount", targetShort);
      // formData.append("targetLongAnswerCount", targetLong);

      if (contextFile) {
        formData.append("contextFile", contextFile);
      } else if (contextText) {
        formData.append("contextText", contextText); // Send as text
      }
      
      // const generatedQuestions = await axios.post(`/api/quiz-sets/${quizData.id}/generate-fixed`, formData, { headers: { 'Content-Type': 'multipart/form-data' } });
      const generatedQuestions = await generateFixedQuizAPI(quizData.id, {
        aiPrompt, contextText, contextFile, targetMcq, targetShort
      });

      setQuizData(prev => ({ ...prev, questions: generatedQuestions, source: 'ai_instructor_generated' }));
      toast.success("Quiz questions generated by AI!");
    } catch (error) {
      toast.error("AI generation failed. " + (error.response?.data?.message || error.message));
      console.error(error);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="mt-6 border  rounded-md p-4 space-y-6">
      <div>
        <Label htmlFor="aiPrompt">Custom Prompt (Optional)</Label>
        <Textarea
          id="aiPrompt"
          value={aiPrompt}
          onChange={(e) => setAiPrompt(e.target.value)}
          placeholder="e.g., Generate questions focusing on the key concepts of Chapter 3..."
          rows={3}
          disabled={isGenerating}
        />
      </div>
      <div>
        <Label htmlFor="contextText">Context Data (Paste Text)</Label>
        <Textarea
          id="contextText"
          value={contextText}
          onChange={(e) => setContextText(e.target.value)}
          placeholder="Paste your document text here..."
          rows={8}
          disabled={isGenerating || !!contextFile}
        />
      </div>
      <div className="text-sm text-center my-2">OR</div>
      <div>
        <Label htmlFor="contextFile">Context Data (Upload PDF, DOCX, TXT)</Label>
        <Input
          id="contextFile"
          type="file"
          accept=".pdf,.docx,.txt"
          onChange={handleFileChange}
          disabled={isGenerating || !!contextText}
        />
        {contextFile && <p className="text-xs mt-1">Selected: {contextFile.name}</p>}
      </div>
      <div className="grid grid-cols-2 gap-4">
        <div>
          <Label htmlFor="targetMcq">Number of MCQs</Label>
          <Input
            id="targetMcq"
            type="number"
            value={targetMcq}
            onChange={(e) => setTargetMcq(parseInt(e.target.value, 10))}
            min="0"
            disabled={isGenerating}
          />
        </div>
        <div>
          <Label htmlFor="targetShort">Number of Short Answer Questions</Label>
          <Input
            id="targetShort"
            type="number"
            value={targetShort}
            onChange={(e) => setTargetShort(parseInt(e.target.value, 10))}
            min="0"
            disabled={isGenerating}
          />
        </div>
        {/* Add input for Long Answer questions if needed */}
      </div>
      <Button onClick={handleGenerate} disabled={isGenerating} className="w-full">
        {isGenerating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : "Generate Fixed Quiz with AI"}
      </Button>

      {quizData.questions && quizData.questions.length > 0 && quizData.source === 'ai_instructor_generated' && (
        <div className="mt-8">
          <h3 className="text-lg font-semibold mb-2">Generated Questions (Editable)</h3>
          <ManualQuizEditor quizData={quizData} setQuizData={setQuizData} />
        </div>
      )}
    </div>
  );
};