import { HoverEffect } from "./ui/card-hover-effect";
import {
  ArrowRightIcon,
  ArrowRight,
  BookOpen,
  CheckCircle,
  Calendar,
  Brain,
  BarChart3,
  Users,
  Star,
  Sparkles,
  GraduationCap,
  Award,
  Search,
  Filter,
} from "lucide-react";

export function CardHoverEffectDemo() {
  return (
    <div className="max-w-5xl mx-auto px-8">
      <HoverEffect items={projects} />
    </div>
  );
}
export const projects = [
  {
    icon: <GraduationCap className="h-8 w-8 text-white" />,
    title: "Join a Class",
    description:
      "Browse and enroll in classes that match your academic interests and requirements.",
    color: "bg-blue-500",
  },
  {
    icon: <Calendar className="h-8 w-8 text-white" />,
    title: "Weekly Content",
    description:
      "Access structured weekly materials including readings, videos, and resources.",
    color: "bg-purple-500",
  },
  {
    icon: <Brain className="h-8 w-8 text-white" />,
    title: "Take AI Quizzes",
    description:
      "Test your knowledge with customized quizzes generated by our AI system.",
    color: "bg-pink-500",
  },
  {
    icon: <Award className="h-8 w-8 text-white" />,
    title: "Earn Certificates",
    description:
      "Complete courses and earn certificates to showcase your achievements.",
    color: "bg-emerald-500",
  },
];