import { CourseProgress } from "@/components/course-progress";
import { SectionTitle } from "@/components/section-title";
import { Button, buttonVariants } from "@/components/ui/button";
import { formatPrice } from "@/lib/formatPrice";
import { cn } from "@/lib/utils";
import {
  ArrowRightIcon,
  ArrowRight,
  BookOpen,
  CheckCircle,
  Calendar,
  Brain,
  BarChart3,
  Users,
  Star,
  Sparkles,
  GraduationCap,
  Award,
  Search,
  Filter,
} from "lucide-react";

import Image from "next/image";
import Link from "next/link";

import { getCourseList } from "../../queries/courses";

import { getCategories } from "../../queries/categories";
import HeroLottieWrapper from "./_components/HeroLottieWrapper";
import HeroLottie from "./_components/HeroLottie";



//MARK: CATEGORIES

//MARK: features
const features = [
  {
    icon: <Calendar className="h-10 w-10 text-primary" />,
    title: "Week-Based Structure",
    description:
      "Aligned with JUST's academic calendar, our platform organizes content by weeks instead of generic modules.",
  },
  {
    icon: <Brain className="h-10 w-10 text-primary" />,
    title: "AI-Driven Quizzes",
    description:
      "Instructors provide prompts to our AI system, which generates customized quizzes for each week's content.",
  },
  {
    icon: <BarChart3 className="h-10 w-10 text-primary" />,
    title: "Progress Analytics",
    description:
      "Track your learning journey with detailed analytics and personalized feedback on your performance.",
  },
  {
    icon: <Users className="h-10 w-10 text-primary" />,
    title: "Instructor Control",
    description:
      "Teachers can preview, edit, and version control all AI-generated assessments before publishing.",
  },
];
//MARK: howItWorks
const howItWorks = [
  {
    icon: <GraduationCap className="h-8 w-8 text-white" />,
    title: "Join a Class",
    description:
      "Browse and enroll in classes that match your academic interests and requirements.",
    color: "bg-blue-500",
  },
  {
    icon: <Calendar className="h-8 w-8 text-white" />,
    title: "Weekly Content",
    description:
      "Access structured weekly materials including readings, videos, and resources.",
    color: "bg-purple-500",
  },
  {
    icon: <Brain className="h-8 w-8 text-white" />,
    title: "Take AI Quizzes",
    description:
      "Test your knowledge with customized quizzes generated by our AI system.",
    color: "bg-pink-500",
  },
  {
    icon: <Award className="h-8 w-8 text-white" />,
    title: "Earn Certificates",
    description:
      "Complete courses and earn certificates to showcase your achievements.",
    color: "bg-emerald-500",
  },
];
//MARK: courses

const HomePage = async () => {
  // const courseList = await getCourseList();
  const categories = await getCategories();
  const courses = await getCourseList()
  // console.log(" HomePage ~ categories:", categories)


  // console.log("HomePage ~ course:", JSON.stringify(courseList, null, 2));
  // console.dir(course, {
  //   depth: null, // full depth
  //   colors: true, // enable terminal colors
  //   compact: false, // expand everything for readability
  // });

  return (
    <>
      <section className="space-y-6 pb-8 pt-6 md:pb-12 md:pt-10 lg:py-32 ">
        <div className="flex max-w-7xl mx-auto justify-center items-center">
          {/* <HeroLottieWrapper /> */}
          <HeroLottie/>
          
          <div className="container flex max-w-3xl flex-col items-center gap-4 text-center relative isolate">
            <div
              aria-hidden="true"
              className="pointer-events-none absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80"
            >
              <div
                style={{
                  clipPath:
                    "polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)",
                }}
                className="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]"
              />
            </div>

            {/* <span className="rounded-2xl bg-muted px-4 py-1.5 text-sm font-medium border shadow-lg">
            Hey, Welcome
          </span> */}
            <h1 className="font-heading mb-8 text-2xl font-bold sm:text-3xl md:text-4xl lg:text-6xl">
              <span style={{ color: "hsl(var(--primary))" }}>J</span>ust{" "}
              <span style={{ color: "hsl(var(--primary))" }}>U</span>nlock{" "}
              <span style={{ color: "hsl(var(--primary))" }}>S</span>kills{" "}
              <span style={{ color: "hsl(var(--primary))" }}>T</span>hat{" "}
              <span style={{ color: "hsl(var(--primary))" }}>L</span>ead{" "}
              <span style={{ color: "hsl(var(--primary))" }}>E</span>very{" "}
              <span style={{ color: "hsl(var(--primary))" }}>A</span>mbition{" "}
              <span style={{ color: "hsl(var(--primary))" }}>R</span>ight{" "}
              <span style={{ color: "hsl(var(--primary))" }}>N</span>ow.
            </h1>

            <div className="flex items-center gap-3 flex-wrap justify-center">
              <Link href="/courses" className={cn(buttonVariants({ size: "lg" }))}>
                Explore Now
              </Link>
              <Link
                href=""
                className={cn(
                  buttonVariants({ variant: "outline", size: "lg" })
                )}
              >
                Become An Instructor
              </Link>
            </div>
          </div>
        </div>
      </section>
      {/* How It Works Section */}
      <section className="bg-muted/30 py-16 md:py-24">
        <div className="container">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold mb-4">How JUSTLearn Works</h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Our platform is designed to make learning seamless and effective
              for JUST students and faculty.
            </p>
          </div>

          <div className="relative">
            {/* Connection line */}
            {/* <div className="absolute top-1/2 left-0 right-0 h-1 bg-muted hidden md:block"></div> */}

            <div className="grid md:grid-cols-4 gap-8 relative">
              {howItWorks.map((step, index) => (
                <div
                  key={index}
                  className="flex flex-col items-center text-center relative z-10"
                >
                  <div
                    className={`${step.color} w-16 h-16 rounded-full flex items-center justify-center mb-4 shadow-lg`}
                  >
                    {step.icon}
                  </div>
                  <h3 className="text-xl font-semibold mb-2">{step.title}</h3>
                  <p className="text-muted-foreground">{step.description}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="container py-16 md:py-24">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold mb-4">Why Choose JUSTLearn?</h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Our platform is specifically designed for Jashore University of
            Science and Technology, with features that enhance both teaching and
            learning experiences.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <div
              key={index}
              className="bg-card rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow border"
            >
              <div className="mb-4">{feature.icon}</div>
              <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
              <p className="text-muted-foreground">{feature.description}</p>
            </div>
          ))}
        </div>
      </section>
      {/* Categories Section */}
      <section
        id="categories"
        className="container space-y-6  py-8  md:py-12 lg:py-24"
      >
        <div className="flex items-center justify-between">
          <SectionTitle>Categories</SectionTitle>

          <Link
            href={""}
            className=" text-sm font-medium  hover:opacity-80 flex items-center gap-1"
          >
            Browse All <ArrowRightIcon className="h-4 w-4" />
          </Link>
        </div>
        <div className="mx-auto grid justify-center gap-4 grid-cols-2  md:grid-cols-3 2xl:grid-cols-4">
          {categories.map((category) => {
            return (
              <Link
                href={`/category/${category.id}`}
                key={category.id}
                className="relative overflow-hidden rounded-lg border bg-background p-2 hover:scale-105 transition-all duration-500 ease-in-out"
              >
                <div className="flex  flex-col gap-4 items-center justify-between rounded-md p-6">
                  <Image
                    src={`/assets/images/categories/${category.thumbnail}`}
                    alt={category.title}
                    width={100}
                    height={100}
                  />
                  <h3 className="font-bold">{category.title}</h3>
                </div>
              </Link>
            );
          })}
        </div>
      </section>

      {/* Courses */}
      <section id="courses" className="container space-y-6   md:py-12 lg:py-24">
        <div className="flex items-center justify-between">
          <SectionTitle>Courses</SectionTitle>
          <Link
            href={"/courses"}
            className=" text-sm font-medium  hover:opacity-80 flex items-center gap-1"
          >
            Browse All <ArrowRightIcon className="h-4 w-4" />
          </Link>
        </div>
        <div className="grid sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-4 gap-4">
          {courses.map((category) => {
            return (
              <Link key={category.id} href={`/courses/${category.id}`}>
                <div className="group hover:shadow-sm transition overflow-hidden border rounded-lg p-3 h-full">
                  <div className="relative w-full aspect-video rounded-md overflow-hidden">
                    <Image
                      src={`/assets/images/courses/${category.thumbnail}`}
                      alt={"course"}
                      className="object-cover m-4"
                      fill
                    />
                  </div>
                  <div className="flex flex-col pt-2">
                    <div className="text-lg md:text-base font-medium group-hover:text-sky-700 line-clamp-2">
                     {category.title}
                    </div>
                    <p className="text-xs text-muted-foreground">Development</p>
                    <div className="my-3 flex items-center gap-x-2 text-sm md:text-xs">
                      <div className="flex items-center gap-x-1 text-slate-500">
                        <div>
                          <BookOpen className="w-4" />
                        </div>
                        <span>4 Chapters</span>
                      </div>
                    </div>

                    <CourseProgress
                      size="sm"
                      value={80}
                      variant={110 === 100 ? "success" : ""}
                    />

                    <div className="flex items-center justify-between mt-4">
                      <p className="text-md md:text-sm font-medium text-slate-700">
                        {formatPrice(49)}
                      </p>

                      <Button
                        variant="ghost"
                        className="text-xs text-sky-700 h-7 gap-1"
                      >
                        Enroll
                        <ArrowRight className="w-3" />
                      </Button>
                    </div>
                  </div>
                </div>
              </Link>
            );
          })}
        </div>
      </section>
    </>
  );
};
export default HomePage;
