import { SectionTitle } from "@/components/section-title";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import {
  ArrowRightIcon,
  Award,
  BarChart3,
  BookOpen,
  Brain,
  Calendar,
  GraduationCap,
  Users
} from "lucide-react";

import Image from "next/image";
import Link from "next/link";

import { getCourseList } from "../../queries/courses";

import { getCategories } from "../../queries/categories";
import HeroLottieWrapper from "./_components/HeroLottieWrapper";
import HeroSection from "./_components/HeroSection";

//MARK: CATEGORIES

//MARK: features
const features = [
  {
    icon: <Calendar className="h-10 w-10 text-primary" />,
    title: "Week-Based Structure",
    description:
      "Aligned with JUST's academic calendar, our platform organizes content by weeks instead of generic modules.",
  },
  {
    icon: <Brain className="h-10 w-10 text-primary" />,
    title: "AI-Driven Quizzes",
    description:
      "Instructors provide prompts to our AI system, which generates customized quizzes for each week's content.",
  },
  {
    icon: <BarChart3 className="h-10 w-10 text-primary" />,
    title: "Progress Analytics",
    description:
      "Track your learning journey with detailed analytics and personalized feedback on your performance.",
  },
  {
    icon: <Users className="h-10 w-10 text-primary" />,
    title: "Instructor Control",
    description:
      "Teachers can preview, edit, and version control all AI-generated assessments before publishing.",
  },
];
//MARK: howItWorks
const howItWorks = [
  {
    icon: <GraduationCap className="h-8 w-8 text-white" />,
    title: "Join a Class",
    description:
      "Browse and enroll in classes that match your academic interests and requirements.",
    color: "bg-blue-500",
  },
  {
    icon: <Calendar className="h-8 w-8 text-white" />,
    title: "Weekly Content",
    description:
      "Access structured weekly materials including readings, videos, and resources.",
    color: "bg-purple-500",
  },
  {
    icon: <Brain className="h-8 w-8 text-white" />,
    title: "Take AI Quizzes",
    description:
      "Test your knowledge with customized quizzes generated by our AI system.",
    color: "bg-pink-500",
  },
  {
    icon: <Award className="h-8 w-8 text-white" />,
    title: "Earn Certificates",
    description:
      "Complete courses and earn certificates to showcase your achievements.",
    color: "bg-emerald-500",
  },
];
//MARK: courses

const HomePage = async () => {
  // const courseList = await getCourseList();
  console.log("inside home page........");

  // const user = await getAllUsers()
  const fetchedCourse = await getCourseList();
  const courses = fetchedCourse.filter(item=>item.visibility==="public" && item.active===true)
  // console.log(" HomePage ~ courses:", courses)
  const categories = await getCategories();
  // const cc = await getCourseDetails("664aca881387e2ad2e8be484")
  // chalkLog.log(" HomePage ~ courses:", courses)
  // console.log(" HomePage ~ categories:", categories)

  // console.log("HomePage ~ course:", JSON.stringify(courseList, null, 2));
  // console.dir(course, {
  //   depth: null, // full depth
  //   colors: true, // enable terminal colors
  //   compact: false, // expand everything for readability
  // });

  return (
    <>
      <HeroSection/>
      {/* How It Works Section */}
      <section className="bg-muted/30 py-16 md:py-24">
        <div className="container">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold mb-4">How JUSTLearn Works</h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Our platform is designed to make learning seamless and effective
              for JUST students and faculty.
            </p>
          </div>

          <div className="relative">
            {/* Connection line */}
            {/* <div className="absolute top-1/2 left-0 right-0 h-1 bg-muted hidden md:block"></div> */}

            <div className="grid md:grid-cols-4 gap-8 relative">
              {howItWorks.map((step, index) => (
                <div
                  key={index}
                  className="flex flex-col items-center text-center relative z-10"
                >
                  <div
                    className={`${step.color} w-16 h-16 rounded-full flex items-center justify-center mb-4 shadow-lg`}
                  >
                    {step.icon}
                  </div>
                  <h3 className="text-xl font-semibold mb-2">{step.title}</h3>
                  <p className="text-muted-foreground">{step.description}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="container py-16 md:py-24">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold mb-4">Why Choose JUSTLearn?</h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Our platform is specifically designed for Jashore University of
            Science and Technology, with features that enhance both teaching and
            learning experiences.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <div
              key={index}
              className="bg-card rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow border"
            >
              <div className="mb-4">{feature.icon}</div>
              <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
              <p className="text-muted-foreground">{feature.description}</p>
            </div>
          ))}
        </div>
      </section>
      {/* Categories Section */}
      <section
        id="categories"
        className="container space-y-6  py-8  md:py-12 lg:py-24"
      >
        <div className="flex items-center justify-between">
          <SectionTitle>Categories</SectionTitle>
          <Link
            href="/courses"
            className=" text-sm font-medium  hover:opacity-80 flex items-center gap-1"
          >
            Browse All <ArrowRightIcon className="h-4 w-4" />
          </Link>
        </div>
        <div className="mx-auto grid justify-center gap-4 grid-cols-2  md:grid-cols-3 2xl:grid-cols-4">
          {categories.map((category) => (
            <Link
              href={`/courses?categories=${encodeURIComponent(category.title)}`}
              key={category.id}
              className="relative overflow-hidden rounded-lg border bg-background p-2 hover:scale-105 transition-all duration-500 ease-in-out"
            >
              <div className="flex flex-col gap-4 items-center justify-between rounded-md p-2">
                {/* <div className="relative aspect-square max-w-[300px] max-h-[200px] rounded-md overflow-hidden"> */}
                  <Image
                    src={category.thumbnail}
                    alt={category.title}
                    // fill
                    width={300}
                    height={200}
                    className="object-cover"
                  />
                {/* </div> */}
                <h3 className="font-bold text-center">{category.title}</h3>
              </div>
            </Link>
          ))}
        </div>
      </section>

      {/* Courses */}
      <section id="courses" className="container space-y-6   md:py-12 lg:py-24">
        <div className="flex items-center justify-between">
          <SectionTitle>Courses</SectionTitle>
          <Link
            href={"/courses"}
            className=" text-sm font-medium  hover:opacity-80 flex items-center gap-1"
          >
            Browse All <ArrowRightIcon className="h-4 w-4" />
          </Link>
        </div>
        <div className="grid sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-4 gap-4">
          {courses.map((category) => (
            <Link key={category.id} href={`/courses/${category.id}`}>
              <div className="group hover:shadow-sm transition overflow-hidden border rounded-lg p-3 h-full">
                <div className="relative w-full aspect-video rounded-md overflow-hidden">
                  <Image
                    src={category.thumbnail}
                    alt={category.title}
                    fill
                    className="object-cover"
                  />
                </div>
                <div className="flex flex-col pt-2">
                  <div className="text-lg md:text-base font-medium group-hover:text-sky-700 line-clamp-2">
                    {category.title}
                  </div>
                  <p className="text-xs text-muted-foreground">{category?.category?.title}</p>

                  <div className="my-3 flex items-center gap-x-2 text-sm md:text-xs">
                    <div className="flex items-center gap-x-1 text-slate-500">
                      <BookOpen className="w-4" />
                      <span>4 Chapters</span>
                    </div>
                  </div>

                  {/* <CourseProgress
                    size="sm"
                    value={80}
                    variant={110 === 100 ? "success" : ""}
                  /> */}

                  
                </div>
              </div>
            </Link>
          ))}
        </div>
      </section>
    </>
  );
};
export default HomePage;
